---
title: "bias_explore"
author: "Robert Heilmayr"
date: "August 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('quickmontey.R')

```


Define universal parameters
```{r parameters}
b0 = .05
b1 = -0.25
b2 = -0.1
b3 = .16
std_a = .1
std_v = 0.25
years = 3
nobs = 10000
n = 100
```


#Monte Carlo version
Notice addition of new parameters (std_a, std_v, outcome) to simplify modifications
Results in significant bias.
```{r mc}
results <- quickmontey(n, nobs, years, b0, b1, b2, b3, std_a, std_v, "y")
results$plot
```


# Simplified version 
Just estimate latent variable for each of n observations with and without b3. Calculate ATE and compare to computed ATE
Results in no bias (especially as you push n / nobs to inf)
```{r simple}
ATE <- pnorm(b0+b1+b2+b3, 0, (std_a^2+std_v^2)^.5) - pnorm(b0+b1+b2, 0, (std_a^2+std_v^2)^.5)
coeffmatrix <- matrix(nrow = n, ncol = 1)

for(i in 1:n){
  a <- rnorm(n = nobs, 0, std_a)
  v <- rnorm(n = nobs, 0, std_v)
  y_star <- (b0 + b1 + b2 + b3 + a + v)
  y <- y_star>0
  y_cf_star <- (b0 + b1 + b2 + a + v)
  y_cf <- y_cf_star>0
  sim_ATE <- mean(y) - mean(y_cf)
  coeffmatrix[i,1] <- (ATE - sim_ATE)
  print(i)
  }  


did_coeff <- as.data.frame(coeffmatrix)
actual <- rep(ATE, times = n)

plot = ggplot() +
  geom_density(data = did_coeff , aes(x = V1), alpha = .2, fill="#29CD44")+
  geom_vline(data = did_coeff, xintercept = mean(did_coeff$V1), color = 'red')+
  geom_vline(data = did_coeff, xintercept = 0, linetype = "dashed")+
  theme(plot.caption = element_text(hjust = 0.5))+
  labs(x= "Bias", caption = paste("Mean:", round(mean(did_coeff$V1), digits = 4),
                                  ", RMSE:", round(rmse(actual, did_coeff$V1), digits = 4)) 
  )
plot
```

