---
title: "outline_sep19"
author: "Alberto Garcia"
date: "September 3, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('quickmontey.R')
source('binary_coeffdist_fcn.R')
source('funcform.R')
source('grid_scapegen.R')
source('grid_sim.R')
source('property_scapegen.R')
source('weightedreg_test.R')
source('property_perturb.R')

```

Define universal parameters
```{r parameters}
b0 = .05
b1 = -0.1
b2 = -0.2
b3 = .16
std_a = .1
std_v = 0.25
years = 3
nobs = 10000
n = 100
cellsize = 20
ppoints = 200
std_p = .1
```



```{r DIDy}
DID_y <- quickmontey(n, nobs, years, b0, b1, b2, b3, std_a, std_v, "y")
DID_y$plot
```

```{r DIDy_it}
DID_yit <- quickmontey(n, nobs, years, b0, b1, b2, b3, std_a, std_v, "y_it")
DID_yit$plot
```


```{r FE}
twowayFE <- binary_coeffdist_fcn(n, nobs, years, b0, b1, b2, b3, std_a, std_v)
twowayFE$plot
```




```{r functionalforms}
functionalform <- funcform(n, nobs, years, b0, b1, b2, b3, std_a, std_v)
functionalform$plot
```


```{r outcomes}
outcomes <- outcome_comparison(n, nobs, years, b0, b1, b2, b3, std_a, std_v, cellsize)
outcomes$plot
```




```{r grids}
grid <- grid_sim(n, nobs, years, b0, b1, b2, b3, std_a, std_v, cellsize)
grid$plot
```






```{r weighting}
weighting <- weightedreg_test(n, nobs, years, b0, b1, b2, b3, std_a, std_v, std_p, cellsize, ppoints)
weighting$plot
```



```{r property_perturbations}
perturb <- property_perturb(n, nobs, years, b0, b1, b2, b3, std_a, std_v, std_p, cellsize, ppoints)
perturb$plot
```

