---
title: "final_outline"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# plots
source('did_trends.R')

#binary fcns
source('quickmonte.R')
source('TWFE_fcn.R')
source('DID_keep.R')
source('functionalform.R')
source('functionalform_agg.R')

source('outcome_fcn.R')
source('aggregation_fcn.R')
source('aggregate_complete.R') #aggreagate_complete is the function we'll use most in this outline, as it runs all combinations and generates summary dataframe to be used for specification chart
source('layerprocess_fcn.R')

source('vary_outcome_defor.R')
source('vary_outcome_yr.R')
source('vary_rate_funcform.R')
source('vary_rate_funcform_agg.R')

source('landscape_map.R')

```


```{r generating landscape parameters, results='hide'}

base_0 = .02
base_1 = .05
trend = -.005
ATT = -.01

std_a = 0.1
std_v = 0.25
years = 3
nobs = 10000
n = 200

cellsize = 10
ppoints = 50
std_p = 0
cpoints = 20


```

```{r}

# generate landscape plot
landscape_map <- landscape_map(nobs, years, b0, b1, b2, b3, std_a = 0.1, std_v = 0.25, std_p = .1, cellsize, ppoints, cpoints)$landscape_period2_counter


```


```{r aggregate, results = 'hide', warning=FALSE}

# we'll need to recompute the parameters if we change the value of sigma_p
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

# summary function that estimates all of the different specifications
aggregation <- aggregate_complete(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)

#outputs density plots of estimate distributions
#aggregation$plot
#aggregation$fe_plot

# activate ggsave below in order to save density plots
#ggsave(plot = aggregation$plot, path = "figs", filename = "aggregated_ua.png", dpi = 500)
#ggsave(plot = aggregation$fe_plot, path = "figs", filename = "aggregated_fe.png", dpi = 500)


# We save the summary measures of the bias and coverage for a subset of the specifications
bias_0 <- aggregation$biases
fe_bias_0 <- aggregation$fe_biases
did_cover_0 <- aggregation$did_coverages_df
fe_cover_0 <- aggregation$fe_coverages_df
agg_cover_0 <- aggregation$agg_coverages_df

summary_df <- aggregation$summary_df[2:12,]
# write.csv(summary_df, "summary_df.csv")
# Looks better when there is an outer margins
par(oma=c(1,0,1,1))

labels <- list("Unit of analysis:" = c("pixel", "grid", "property", "county"),
               "Fixed effects:" = c("pixel FE", "grid FE", "property FE", "county FE", "treatment FE"),
               "SE structure:" = c("clustered at pixel", "clustered at grid", "clustered at property", "clustered at county"))

coverage <- summary_df$cover
RMSE <- summary_df$RMSE
test <- subset(summary_df, select=-c(cover, RMSE))

index.ci <- match(c("q05","q95"), names(test))

# One could also add information about model fit to this chart
ylim <- c(-0.035,0.04)

topline = -0.015

midline = topline-0.02-.0025

ylim <- c(midline-.02,0.04)
#bottomline = (min(ylim)+topline)/2
#Create the plot


schart(test,labels, ylim = ylim, index.ci=index.ci, col.est=c("grey50","#D55E00"), ylab="Bias", highlight=1
       ,band.ref=c(-.05, .04)
       , axes = FALSE
       #, col.band.ref="#c7e9f9"
) # make some room at the bottom
Axis(side=2, at = c( 0, 0.03), labels=TRUE)
abline(h=topline)
abline(h=midline)
#abline(h=bottomline)
lapply(1:length(RMSE), function(i) {
 # text(x= i, y=min(ylim)+.002, paste0(i), col="black", font=2, cex = 1)
  mtext(paste0(i), side=1, at = i, font=2, cex=.95)#, line=1, at=-1)
  text(x= i, y=midline+0.005, paste0(round(RMSE[i], digits = 4)), col="black", font=1, cex=.9)
  text(x= i, y=min(ylim)+0.0025, paste0(round(coverage[i], digits = 3)), col="black", font=1, cex=.9 )
})
# mtext('coverage\nprobability', side=2, las=1, at = loc_1, adj = 1, font=2, line=1)
# mtext('RMSE', side=2, las=1, at = loc_2, font=2, line=1)
text(x=mean(1:nrow(test))
     , y=midline-.005, "coverage probability (95% desired)", col="black", font=2)
text(x=mean(1:nrow(test))
    , y=topline-.005, "RMSE", col="black", font=2)
legend(x=6.5, y=0.05, col = "grey50", legend = "0.05 to 0.95 quantile \n of estimate distribution", seg.len=0.65, inset = 0.005,  box.lty=0, cex=0.8, lty = 1, lwd = 4, bg="transparent")


summary0_df <- aggregation$summary_df[2:12,]%>%
  mutate(sigma_p=0)


```


```{r aggregate sig_p 1, results = 'hide', warning=FALSE}
std_p = 0.1
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

aggregation_1 <- aggregate_complete(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
#aggregation_5$plot
#ggsave(path = "figs", filename = "aggregation.png", dpi = 500)


bias_1 <- aggregation_1$biases
fe_bias_1 <- aggregation_1$fe_biases
cover_1 <- aggregation_1$coverages_df
fe_cover_1 <- aggregation_1$fe_coverages_df

summary1_df <- aggregation_1$summary_df[2:12,]%>%
  mutate(sigma_p=.1)

```

```{r aggregate sig_p 2, results = 'hide', warning=FALSE}
std_p = 0.2
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

aggregation_2 <- aggregate_complete(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
# aggregation_25$plot

bias_2 <- aggregation_2$biases
fe_bias_2 <- aggregation_2$fe_biases
cover_2 <- aggregation_2$coverages_df
fe_cover_2 <- aggregation_2$fe_coverages_df

summary2_df <- aggregation_2$summary_df[2:12,]%>%
  mutate(sigma_p=.2)

```

```{r aggregate sig_p 3, results = 'hide', warning=FALSE}
std_p = 0.3
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

aggregation_3 <- aggregate_complete(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
# aggregation_25$plot

bias_3 <- aggregation_3$biases
fe_bias_3 <- aggregation_3$fe_biases
cover_3 <- aggregation_3$coverages_df
fe_cover_3 <- aggregation_3$fe_coverages_df

summary3_df <- aggregation_3$summary_df[2:12,]%>%
  mutate(sigma_p = .3)

```

```{r agg bias and rmse, results = 'hide', warning=FALSE}

# creating RMSE csv
RMSE <- function (x) sqrt(mean((x-0)^2))
rmse_p <- data.frame(
  "0" = unlist(lapply(bias_0, FUN = RMSE)),
  "0.1" = unlist(lapply(bias_1, FUN = RMSE)),
  "0.2" = unlist(lapply(bias_2, FUN = RMSE)),
  "0.3" = unlist(lapply(bias_3, FUN = RMSE))
  , check.names = FALSE
)

fe_rmse_p <- data.frame(
  "0" = unlist(lapply(fe_bias_0, FUN = RMSE)),
  "0.1" = unlist(lapply(fe_bias_1, FUN = RMSE)),
  "0.2" = unlist(lapply(fe_bias_2, FUN = RMSE)),
  "0.3" = unlist(lapply(fe_bias_3, FUN = RMSE))
  , check.names = FALSE
)

write.csv(rmse_p, "rmse_p.csv")
write.csv(fe_rmse_p, "fe_rmse_p.csv")

# creating bias csv
biases_p <- data.frame("0" = colMeans(bias_0) , "0.1" = colMeans(bias_1), "0.2" = colMeans(bias_2), "0.3" = colMeans(bias_3) ,check.names = FALSE)

fe_biases_p <- data.frame("0" = colMeans(fe_bias_0) , "0.1" = colMeans(fe_bias_1), "0.2" = colMeans(fe_bias_2), "0.3" = colMeans(fe_bias_3) ,check.names = FALSE)

biases_p <- rbind(biases_p, fe_biases_p)

write.csv(biases_p, "bias_p.csv")
write.csv(fe_biases_p, "fe_bias_p.csv")
```


```{r coverage}
did_coverage <- did_cover_0 %>%
  mutate(did_cover_1 = did_cover_1[,ncol(did_cover_1)],
         did_cover_2 = did_cover_2[,ncol(did_cover_2)],
         did_cover_3 = did_cover_3[,ncol(did_cover_3)]
         )

agg_coverage <- agg_cover_0 %>%
  mutate(agg_cover_1 = agg_cover_1[,ncol(agg_cover_1)],
         agg_cover_2 = agg_cover_2[,ncol(agg_cover_2)],
         agg_cover_3 = agg_cover_3[,ncol(agg_cover_3)]
         )
  
fe_coverage <-  fe_cover_0 %>%
  mutate(fe_cover_1 = fe_cover_1[,ncol(fe_cover_1)],
         fe_cover_2 = fe_cover_2[,ncol(fe_cover_2)],
         fe_cover_3 = fe_cover_3[,ncol(fe_cover_3)]
         ) 
  
write.csv(did_coverage, "did_coverage.csv")  
write.csv(agg_coverage, "agg_coverage.csv") 
write.csv(fe_coverage, "fe_coverage.csv")  

```


```{r plot rmse, results = 'hide', warning=FALSE}

rmse_plot_df <- rbind(rmse_p, fe_rmse_p) %>%
  rownames_to_column(var = "model") %>%
  melt(variable.name = "sigma_p", value.name = "RMSE" )%>%
  separate(model, into = c("fixed effects", "uoa"), sep = " ")%>%
  mutate("unit of analysis" = ifelse(is.na(uoa),  "same as fe", "pixel"),
         "fixed effects" = ifelse(`fixed effects`=="pixel", "none", `fixed effects`)
         )

plot_rmse = ggplot(data = rmse_plot_df, aes(x = as.numeric(as.character(sigma_p)), y = RMSE,  linetype = `unit of analysis`, colour = `fixed effects`)) +
    geom_line(size = 1.25) +
  geom_segment(aes(x=0, xend=.3, y=0, yend=0), linetype = "dashed", size=1, color="black")+
  geom_vline(xintercept = 0, size=1)+
    #theme(plot.caption = element_text(hjust = 0.5))+
    labs(y = "RMSE", x= expression(sigma[p]))+
  ggtitle(expression(paste("RMSE as a function of ", sigma[p])))+
  # theme_classic() +
  #scale_color_colorblind()+
  mytheme
plot_rmse

ggsave(path = "figs", filename = "rmse_p.png", dpi = 500)

biases_p <- read.csv("bias_p.csv",check.names=FALSE,row.names = 1)[1:4,]

bias_plot_df <- biases_p %>%
  rownames_to_column(var = "unit of analysis") %>%
  melt(variable.name = "sigma_p", value.name = "bias" )%>%
  filter(`unit of analysis` !="pixel")

mytheme <- theme(#axis.line = element_line(size = 1, colour = "black"),
                 panel.grid.major  = element_line(colour="grey", size=rel(0.5)),
                 panel.grid.minor = element_blank(),
                 panel.background = element_rect(fill="whitesmoke"),
                 plot.title= element_text(hjust = 0.5))

cbPalette <- c("pixel (DID)" = "#E69F00", county = "#56B4E9", grid = "#009E73", property ="#D55E00")#, "#CC79A7",  "#0072B2")

plot_bias = ggplot(data = bias_plot_df, aes(x = as.numeric(as.character(sigma_p)), y = bias, colour = `unit of analysis`)) +
  ylim(-.005, .0005)+
    geom_line(size = 1) +
  geom_segment(aes(x=0, xend=.3, y=0, yend=0), linetype = "dashed", size=.25, color="black")+
  geom_vline(xintercept = 0, size=.25)+
    #theme(plot.caption = element_text(hjust = 0.5))+
    labs(y = "coefficient bias", x= expression(sigma[p]), colour = "unit of analysis")+
  ggtitle(expression(paste("coefficient bias vs. ", sigma[p], " by unit of analysis")))+
   #theme_classic() +
  #scale_colour_manual(values=cbPalette)+
  theme_minimal()+
  theme(plot.title= element_text(hjust = 0.5))
plot_bias

ggsave(path = "figs", filename = "bias_uoa.png", dpi = 500)

```

```{r plot fe rmse, results = 'hide', warning=FALSE}

fe_rmse_plot_df <- fe_rmse_p %>%
  rownames_to_column(var = "fe") %>%
  melt(variable.name = "sigma_p", value.name = "RMSE" )%>%
  separate(fe, into = c("fixed effects", "uoa"), sep = " ")
  

fe_plot_rmse = ggplot(data = fe_rmse_plot_df, aes(x = as.numeric(as.character(sigma_p)), y = RMSE, colour = `fixed effects`)) +
    geom_line(size = 1.1) +
  geom_segment(aes(x=0, xend=.3, y=0, yend=0), linetype = "dashed", size=1.1, color="black")+
  geom_vline(xintercept = 0, size=1.1)+
    #theme(plot.caption = element_text(hjust = 0.5))+
    labs(y = "coefficient bias", x= expression(sigma[p]), colour = "fixed effects")+
  ggtitle(expression(paste("coefficient bias as a function of ", sigma[p])))+
  # theme_classic() +
  scale_colour_manual(values=cbPalette)+
  mytheme
fe_plot_rmse

ggsave(path = "figs", filename = "fe_rmse_p.png", dpi = 500)

fe_biases_p <- read.csv("fe_bias_p.csv",check.names=FALSE,row.names = 1)

did_plot_df <- biases_p %>%
  rownames_to_column(var = "fe") %>%
  filter(fe=="pixel")%>%
  mutate(fe = "treatment")

fe_bias_plot_df <- fe_biases_p %>%
  rownames_to_column(var = "fe") %>%
  bind_rows(did_plot_df)%>%
  melt(variable.name = "sigma_p", value.name = "bias" )%>%
  separate(fe, into = c("fixed effects", "uoa"), sep = " ")

fe_plot_bias = ggplot(data = fe_bias_plot_df, aes(x = as.numeric(as.character(sigma_p)), y = bias, colour = `fixed effects`)) +
  ylim(-.005, .0005)+
    geom_line(size = 1) +
  geom_segment(aes(x=0, xend=.3, y=0, yend=0), linetype = "dashed", size=.25, color="black")+
  geom_vline(xintercept = 0, size=.25)+
    #theme(plot.caption = element_text(hjust = 0.5))+
    labs(y = "coefficient bias", x= expression(sigma[p]), colour = "fixed effects")+
  ggtitle(expression(paste("coefficient bias vs. ", sigma[p], " by fixed effects level")))+
 theme_minimal() +
  theme(plot.title= element_text(hjust = 0.5))
  #scale_colour_manual(values=cbPalette)
  # mytheme
fe_plot_bias

ggsave(path = "figs", filename = "bias_fe.png", dpi = 500)

```

```{r}

full_summary <- rbind(summary0_df, summary1_df, summary2_df, summary3_df)


