---
title: "deforestation econometrics data generating process"
#author: "Alberto Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{amsmath}
  \usepackage{amsfonts} 
  \usepackage{amssymb} 
  \usepackage{graphicx} 
  \usepackage{float} 
  \usepackage{bbm} 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# plots
source('did_trends.R')

#binary fcns
source('quickmonte.R')
source('TWFE_fcn.R')
source('DID_keep.R')
source('functionalform.R')
source('functionalform_agg.R')

source('outcome_fcn.R')
source('aggregation_fcn.R')
source('layerprocess_fcn.R')

source('vary_outcome_defor.R')
source('vary_outcome_yr.R')
source('vary_rate_funcform.R')
source('vary_rate_funcform_agg.R')

```


```{r generating beta parameters, results='hide'}

base_0 = .02
base_1 = .05
trend = -.005
ATT = -.01

std_a = 0.1
std_v = 0.25
years = 3
nobs = 10000
n = 200

cellsize = 10
ppoints = 35
std_p = 0
cpoints = 20
std_c = 0 

std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

```

```{r did trends, results='hide'}

# trends <- did_trends(years, b0, b1, b2_0, b2_1, b3, std_a, std_v)
# 
# trends$plot
# 
# ggsave(path = "figs", filename = "trends.png", dpi = 500)

# landscape_period2
# ggsave(path = "figs", filename = "landscape_2period.png", dpi = 500)

```

### DID allowing outcome to vary between 0 and 1 across periods

```{r did y, results='hide'}

DID_y <- quickmonte(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, "y")

DID_y$plot

ggsave(path = "figs", filename = "did_y.png", dpi = 500)

```

```{r did yit, results='hide'}

DID_yit <- quickmonte(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, "y_it")

DID_yit$plot

#ggsave(path = "figs", filename = "did_yit.png", dpi = 500)

```


```{r functionalform 1, results='hide'}


func <- functionalform(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v)

func$plot

ggsave(path = "figs", filename = "func1.png", dpi = 500)

```

```{r did keep and drop, results='hide'}

did_keep <- DID_keep(n, nobs, b0, b1, b2_0, b2_1, b3, std_a, std_v)

did_keep$plot

ggsave(path = "figs", filename = "DID_keep.png", dpi = 500)

```

```{r functionalform  agg, results='hide'}


func_agg <- functionalform_agg(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, cellsize)

func_agg$plot

ggsave(path = "figs", filename = "func_agg.png", dpi = 500)

```

```{r TWFE, results='hide'}

twoway <- TWFE_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v)

twoway$plot

ggsave(path = "figs", filename = "twoway.png", dpi = 500)


```



```{r outcome 1, results='hide'}

outcome <- outcome_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, cellsize)

outcome$plot

ggsave(path = "figs", filename = "outcome.png", dpi = 500)

```

```{r aggregate, results = 'hide', warning=FALSE}
aggregation <- aggregation_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
aggregation$plot

#ggsave(path = "figs", filename = "aggregation.png", dpi = 500)

#agg_biases <- aggregation$biases
#write.csv(agg_biases, "agg_biases.csv")


# coverages_df <- aggregation$coverages_df
# write.csv(coverages_df, "coverages.csv")

```


```{r aggregate p_err5, results = 'hide', warning=FALSE}
std_p = 0.05
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

aggregation_5 <- aggregation_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
#aggregation_5$plot
#ggsave(path = "figs", filename = "aggregation.png", dpi = 500)

agg_biases_5 <- aggregation_5$biases
#write.csv(agg_biases_5, "agg_biases_5.csv")

coverages5 <- aggregation_5$coverages_df
#write.csv(coverages5, "coverages_p5.csv")

```

```{r aggregate p_err15, results = 'hide', warning=FALSE}
std_p = 0.15
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

aggregation_15 <- aggregation_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
#aggregation_5$plot
#ggsave(path = "figs", filename = "aggregation.png", dpi = 500)

agg_biases_15 <- aggregation_15$biases
#write.csv(agg_biases_15, "agg_biases_15.csv")

coverages15 <- aggregation_15$coverages_df
write.csv(coverages15, "coverages_p15.csv")

```


```{r aggregate p_err25, results = 'hide', warning=FALSE}
std_p = 0.25
std_avp = (std_a^2+std_v^2+std_p^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avp)
b1 = qnorm(base_1, mean = 0, sd = std_avp) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avp) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avp) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avp) + ATT , mean = 0, sd = std_avp) - (b0 + b1 + b2_1)

aggregation_25 <- aggregation_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
# aggregation_25$plot

agg_biases_25 <- aggregation_25$biases
# write.csv(agg_biases_25, "agg_biases_25.csv")

coverages25 <- aggregation_25$coverages_df
write.csv(coverages25, "coverages_p25.csv")

# pixelcounty_25 <- pixelcluster_fcn(100, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, cellsize, ppoints, cpoints)
# 
# cover_pixelcounty_25 <- pixelcounty_25$covermat

```

```{r agg bias and rmse, results = 'hide', warning=FALSE}

# creating RMSE csv
RMSE <- function (x) sqrt(mean((x-0)^2))
rmse_p <- data.frame(
  "0" = unlist(lapply(agg_biases, FUN = RMSE)),
  "0.05" = unlist(lapply(agg_biases_5, FUN = RMSE)),
  "0.15" = unlist(lapply(agg_biases_15, FUN = RMSE)),
  "0.25" = unlist(lapply(agg_biases_25, FUN = RMSE))
  , check.names = FALSE
)
write.csv(rmse_p, "rmse_p.csv")

# creating bias csv
biases_p <- data.frame("0" = colMeans(agg_biases) , "0.05" = colMeans(agg_biases_5), "0.15" = colMeans(agg_biases_15), "0.25" = colMeans(agg_biases_25) ,check.names = FALSE)
write.csv(rmse_p, "bias_p.csv")

```

```{r plot rmse, results = 'hide', warning=FALSE}

rmse_plot_df <- rmse_p %>%
  rownames_to_column(var = "aggregation") %>%
  melt(variable.name = "sigma_p", value.name = "RMSE" )

plot_rmse = ggplot(data = rmse_plot_df, aes(x = as.numeric(as.character(sigma_p)), y = RMSE, colour = aggregation)) +
    geom_line(size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed")+
    theme(plot.caption = element_text(hjust = 0.5))+
    labs(x= "standard error of property level disturbances")
plot_rmse

ggsave(path = "figs", filename = "rmse_p.png", dpi = 500)

bias_plot_df <- biases_p %>%
  rownames_to_column(var = "aggregation") %>%
  melt(variable.name = "sigma_p", value.name = "bias" )

plot_bias = ggplot(data = bias_plot_df, aes(x = as.numeric(as.character(sigma_p)), y = bias, colour = aggregation)) +
    geom_line(size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed")+
    theme(plot.caption = element_text(hjust = 0.5))+
    labs(x= "standard error of property level disturbances")
plot_bias

ggsave(path = "figs", filename = "bias_p.png", dpi = 500)

```


```{r outcome by yr, results = 'hide', warning=FALSE}
base_0 = .02
base_1 = .05
trend = 0
ATT = 0
n = 50
years_min = 2
years_max = 8

yr_outcome1 <- vary_outcome_yr(n, nobs, years_min, years_max, ATT, trend, base_0, base_1, std_a, std_v, cellsize)
yr_outcome1$plot
ggsave(path = "figs", filename = "outcome_byyr1.png", dpi = 500)

yr_outcome2 <- vary_outcome_yr(n, nobs, years_min, years_max, ATT, trend, base_1, base_0, std_a, std_v, cellsize)
yr_outcome2$plot

ggsave(path = "figs", filename = "outcome_byyr2.png", dpi = 500)

```


```{r county level perturbations, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c0 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c0 <- layer_c0$biases
write.csv(layerbiases_c0, "layerbiases_c0.csv")

coverages_c0 <- layer_c0$coverages_df
write.csv(coverages_c0, "coverages_c0.csv")

```

```{r county level perturbations c.05, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0.05
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c5 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c5 <- layer_c5$biases
write.csv(layerbiases_c5, "layerbiases_c5.csv")

coverages_c5 <- layer_c5$coverages_df
write.csv(coverages_c5, "coverages_c5.csv")

```
```{r county level perturbations c.15, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0.1
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c10 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c10 <- layer_c15$biases
write.csv(layerbiases_c10, "layerbiases_c10.csv")

coverages_c10 <- layer_c10$coverages_df
write.csv(coverages_c10, "coverages_c10.csv")

```

```{r county level perturbations c.15, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0.15
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c15 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c15 <- layer_c15$biases
write.csv(layerbiases_c15, "layerbiases_c15.csv")

coverages_c15 <- layer_c15$coverages_df
write.csv(coverages_c15, "coverages_c15.csv")

```


```{r county level perturbations c.2, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0.2
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c2 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c2 <- layer_c2$biases
write.csv(layerbiases_c2, "layerbiases_c2.csv")

coverages_c2 <- layer_c2$coverages_df
write.csv(coverages_c2, "coverages_c2.csv")

```

```{r county level perturbations c.25, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0.25
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c25 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c25 <- layer_c25$biases
write.csv(layerbiases_c25, "layerbiases_c25.csv")

coverages_c25 <- layer_c25$coverages_df
write.csv(coverages_c25, "coverages_c25.csv")

```

```{r county level perturbations c.30, results = 'hide', warning=FALSE}

std_p = 0.15
std_c = 0.3
std_avpc = (std_a^2+std_v^2+std_p^2 + std_c^2)^.5
b0 = qnorm(base_0, mean = 0, sd = std_avpc)
b1 = qnorm(base_1, mean = 0, sd = std_avpc) - b0
b2_0 = qnorm(trend + base_0, mean = 0, sd = std_avpc) - b0
b2_1 = qnorm(trend + base_1, mean = 0, sd = std_avpc) - b0 - b1
b3 = qnorm( pnorm(b0+b1+b2_1, mean = 0, sd = std_avpc) + ATT , mean = 0, sd = std_avpc) - (b0 + b1 + b2_1)

layer_c3 <- layerprocess_fcn(n, nobs, years, b0, b1, b2_0, b2_1, b3, std_a, std_v, std_p, std_c, cellsize, ppoints, cpoints)

layerbiases_c3 <- layer_c3$biases
write.csv(layerbiases_c3, "layerbiases_c3.csv")

coverages_c3 <- layer_c3$coverages_df
write.csv(coverages_c3, "coverages_c3.csv")

```





```{r agg bias and rmse, results = 'hide', warning=FALSE}

# creating RMSE csv
RMSE <- function (x) sqrt(mean((x-0)^2))
rmse_c <- data.frame(
  "0" = unlist(lapply(layerbiases_c0, FUN = RMSE)),
  "0.05" = unlist(lapply(layerbiases_c5, FUN = RMSE)),
  "0.10" = unlist(lapply(layerbiases_c10, FUN = RMSE)),
  "0.15" = unlist(lapply(layerbiases_c15, FUN = RMSE)),
  "0.25" = unlist(lapply(layerbiases_c25, FUN = RMSE))
  , check.names = FALSE
)
write.csv(rmse_c, "rmse_c.csv")

# creating bias csv
biases_c <- data.frame("0" = colMeans(layerbiases_c0) , "0.05" = colMeans(layerbiases_c5), "0.10" = colMeans(layerbiases_c10),"0.15" = colMeans(layerbiases_c15), "0.25" = colMeans(layerbiases_c25)#, "0.3" = colMeans(layerbiases_c3) ,check.names = FALSE)
write.csv(rmse_c, "bias_c.csv")

```

```{r plot layered, results = 'hide', warning=FALSE}

rmse_countyplot_df <- rmse_c %>%
  rownames_to_column(var = "aggregation") %>%
  melt(variable.name = "sigma_c", value.name = "RMSE" )

countyplot_rmse = ggplot(data = rmse_countyplot_df, aes(x = as.numeric(as.character(sigma_c)), y = RMSE, colour = aggregation)) +
    geom_line(size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed")+
    theme(plot.caption = element_text(hjust = 0.5))+
    labs(x= "standard error of county level disturbances")
countyplot_rmse

#ggsave(path = "figs", filename = "rmse_p.png", dpi = 500)

bias_cplot_df <- biases_c %>%
  rownames_to_column(var = "aggregation") %>%
  melt(variable.name = "sigma_c", value.name = "bias" )

cplot_bias = ggplot(data = bias_cplot_df, aes(x = as.numeric(as.character(sigma_c)), y = bias, colour = aggregation)) +
    geom_line(size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed")+
    theme(plot.caption = element_text(hjust = 0.5))+
    labs(x= "standard error of county level disturbances")
cplot_bias

#ggsave(path = "figs", filename = "bias_p.png", dpi = 500)

coverage_cp <- read.csv("coverages_c0.csv") %>%
  mutate(".05" = read.csv("coverages_c5.csv")[,4],
         "0.10" = read.csv("coverages_c10.csv")[,4],
         "0.15" = read.csv("coverages_c15.csv")[,4],
         "0.20" = read.csv("coverages_c2.csv")[,4],
         "0.25" = read.csv("coverages_c25.csv")[,4],
         #"0.3" = read.csv("coverages_c3.csv")[,4]
         )%>%
  rename("0" = coverage)%>%
  arrange(desc(aggregation), std_error)%>%
  filter(aggregation=="county" | aggregation=="property" )%>%
  select(-c(X, std_error))

write.csv(coverage_cp, "coverages_county.csv")

coverage_cerr <- coverage_cp %>%
  melt(variable.name = "sigma_c", value.name = "coverage" )
  

cplot_coverage = ggplot(data = coverage_cerr, aes(x = as.numeric(as.character(sigma_c)), y = coverage, colour = aggregation)) +
    geom_line(size = 1.2) +
  geom_hline(yintercept = 0.95, linetype = "dashed")+
    theme(plot.caption = element_text(hjust = 0.5))+
    labs(x= "standard error of county level disturbances")
cplot_coverage

ggsave(path = "figs", filename = "coverages_county.png", dpi = 500)
```

